### ISSUE TITLE
Typo?

### ISSUE THREAD

**Issue by NathanKell** [ChrisAdderley/HeatControl#1]
https://github.com/ChrisAdderley/HeatControl/blob/master/CModuleHeatPipe.cs#L110
Shouldn't it be parent for both? Or am I misunderstanding?

**Comment by ChrisAdderley** [comment]
As far as I determined, parent is the part the modular

**Comment by ChrisAdderley** [comment]
Object starts at, and tar

**Comment by NathanKell** [comment]
I mean, energy_target = targetThermalMass \* targetTemp
so energy_parent should be parent thermal mass \* _parent_ temp.

**Comment by ChrisAdderley** [comment]
Apologies Nathan, my phone is freaking out. I determined that target is where the pipe ends and parent is where it starts.

**Comment by NathanKell** [comment]
Right. And those heat contents aren't actually used (they're commented) but I think there's a typo in the linked one, hence the above comment.

**Comment by ChrisAdderley** [comment]
Ah I see. Yeah, typo. I stopped using that bit of code due to just using a temperature threshold rather than a heat content, for various balance based reasons.

**Comment by ChrisAdderley** [comment]
I will fix the typo though :)

**Comment by NathanKell** [comment]
No great importance, true, but figured I'd point it out as I noticed it, and I know those things can easily go undetected (ask me why I know that :P )
