### ISSUE TITLE
Part Request - 30 deg and half-width graphene radiator panels

### ISSUE THREAD

**Issue by GHrynk** [ChrisAdderley/HeatControl#16]
To more faithfully replicate some early (Stuhlinger) and contemporary NEP spacecraft concepts (such as HOPE and JIMO), an additional set of fixed graphene radiator panels that permit a narrower radiation shadow zone would be useful.  The kludge is to rotate, offset, and overlap the current 45 deg and full-width panels, or use a somewhat less space-efficient stair-step layout.  I haven't tested whether overlapping panels cause a radiative blockage effect...

**Comment by ChrisAdderley** [comment]
Not sure why you closed this, I might actually do it :)

**Comment by ChrisAdderley** [comment]
Scoped for a future update

**Comment by ChrisAdderley** [comment]
Exists now, closing this
