### ISSUE TITLE
Radiators don't seem to work

### ISSUE THREAD

**Issue by pyalot** [ChrisAdderley/HeatControl#2]
When attaching a radiator to a hot part they seem not to transfer any heat.

![2015-12-25_00005](https://cloud.githubusercontent.com/assets/592826/12002867/a163f4ea-ab0b-11e5-9368-b9c267d7a917.jpg)

Internal heat transfer is 0kW and the total heat transfer of the hot part is just -1420kW. Same story in space:

![2015-12-25_00006](https://cloud.githubusercontent.com/assets/592826/12002874/c76704b6-ab0b-11e5-9deb-19be361ad4cb.jpg)

Compare this with the stock XL radiator:

![2015-12-25_00003](https://cloud.githubusercontent.com/assets/592826/12002882/0989d58a-ab0c-11e5-8e4e-eda4bd39b0b4.jpg)

Total heat transfer from the hot part is -45000kW, and the radiator also gets noticably hotter.

**Comment by ChrisAdderley** [comment]
Looks like there was a parameter missing in all the cfgs that made performance much worse than it should have been.

Fixed in https://github.com/ChrisAdderley/HeatControl/commit/990a29526a3cf945cdb64a1832907c1a88bd539a and will be in 0.2.1 later today

**Comment by ChrisAdderley** [comment]
Fixed in 0.2.1
