### ISSUE TITLE
Parts Do Not Show Up

### ISSUE THREAD

**Issue by Phelidai** [ChrisAdderley/HeatControl#36]
Pretty self explanatory. I have tried multiple installs, and looking into the part files (then again, I'm not a coder), but no matter what I've tried, the parts do not show in any part menu, even thermal. Would love to have these radiators for my reactors.

**Comment by ChrisAdderley** [comment]
I can't help much without more information. I would say you are likely having an install issue - that's the most common reason for things not showing up. Make sure the mod file structure is
`KSP_DIR/GameData/HeatControl/Parts/....` - KSP paths mean that it can't be anything else, like `KSP_DIR/GameData/NerteasMods/HeatControl/Parts/...` or anything different.

If this doesn't resolve it, please post your KSP logfile here so I can examine it.

**Comment by Phelidai** [comment]
[KSP.log](https://github.com/ChrisAdderley/HeatControl/files/4271164/KSP.log)

Here's my log.

**Comment by ChrisAdderley** [comment]
Yep, as I suspected your folder structure looks wrong. There is an additional HeatControl folder, I see HeatControl/HeatControl/Parts in the log. Take that inner folder out and make sure there's only one layer.

**Comment by Phelidai** [comment]
Working now. Thank you!
