### ISSUE TITLE
Parts Suggestion: LH2 Boiler and LH2 Boiler Exhaust

### ISSUE THREAD

**Issue by NightShift10125** [ChrisAdderley/HeatControl#42]
While researching the NERV engine I considered the possibility of LH2 as a coolant for reactors or large nuclear engines such as the LV-NGL 'Deliverance'.
This is how I imagine it would work:
The 'LH2 Boiler' would consume LH2 at a speed relative to the total amount of heat stored in craft, the LH2 would be converted into 'Boiled Hydrogen'.
'Boiled Hydrogen' would then have to be "burned" by a 'LH2 Boiler Exhaust', the 'LH2 Boiler Exhaust' will product thrust based on the rate 'Boiled Hydrogen' is generated.

**Comment by ChrisAdderley** [comment]
This is more deep complexity that this mod doesn't really want to deal with
