### ISSUE TITLE
Radiators B9PS SubTypes doesn't switch the Heat Cooling

### ISSUE THREAD

**Issue by yalov** [ChrisAdderley/HeatControl#45]
Garnet Reactor need 800kW Cooling, 
One Third of the Microchannel Graphene Radiator is chosen (660kW):
![image](https://user-images.githubusercontent.com/12796450/155880522-de8701a4-7a4a-43e0-8ef5-26cea90e2e9a.png)

The reactor suppose to overheat, but it is ok.
System Manager and Part Info show that the cooling is default 2000kW:
![image](https://user-images.githubusercontent.com/12796450/155880885-6dfc205d-5cea-4e75-81e3-d7030ce073ec.png)

same is reproduced with the minimal install:
```
Mod DLLs found:
Stock assembly: Assembly-CSharp v0.0.0.0
B9PartSwitch v2.19.0.0 / vv2.19.0
Collide-o-Scope v1.3.1.0 / v1.3.1+Branch.tags-v1.3.1.Sha.be8f18c959e6203eda10bda6439ee775867afd14
DynamicBatteryStorage v1.0.0.0
NearFutureElectrical v1.0.0.0
Stock assembly: KSPSteamCtrlr v0.0.1.35

Folders and files in GameData:
B9PartSwitch
Collide-o-Scope
CommunityResourcePack
DynamicBatteryStorage
HeatControl
NearFutureElectrical
Stock folder: Squad
Stock folder: SquadExpansion
partVolumes-v2.cfg
```

@blowfishpro

**Comment by ChrisAdderley** [comment]
It's not really any kind of priority to fix stuff that interacts with the stock core heat system, my recommendation is to use system heat.
